### PR TITLE
Add Agaric to coops list

### PR DESCRIPTION
**Pull request by mlncn**
Agaric is worker-owned cooperative building websites and providing online technology consulting since 2006.

Thanks for maintaining this list!

### CODE REVIEW

**Comment by hng** [comment]
Awesome! You are also working in Germany? Would be interested to know more!

**Comment by mlncn** [comment]
Well, our German member is currently loosely affiliated.  He is in Hamburg (work sometimes takes him to Berlin also) and we work on a major online newspaper site with him.  Between @dinarcon and myself we visit Germany about once a year.

**Comment by hng** [comment]
I'd like to know more, maybe there are possibilities for cooperation? How can I contact you (via mail?)?

**Comment by mlncn** [comment]
Yup ask at agaric.com gets to us (i have to double-check that it works on .coop too..)

**Pull request merged**
