### PR TITLE
Add Sustainability Solutions Group co-op

### PR DESCRIPTION
**Pull request by zaneselvans**
They're a Canadian worker co-op with offices all across the country: https://www.ssg.coop/

Maybe not strictly a "tech co-op" but they do geospatial analyses, scenario modeling, and generally data-informed policy work, so I think there's enough overlap to be interesting.

### CODE REVIEW

**Comment by zaneselvans** [comment]
Is there anything I need to do to get this merged?

**Comment by hng** [comment]
It's a bit hard to decide whether they qualify with the definition we use for this list: 

> Tech cooperatives are worker-owned cooperatives that operate in the information technology industry. This list focuses on tech coops that are providing software development and consulting services.

Do you think they fit it?

**Comment by zaneselvans** [comment]
They have several lines of business, many of which are more policy oriented, but the scenario modeling / geospatial analysis seemed like it fit into the category. It seems like they do the data analysis & modeling in house and then generate interactive frontends or static graphical outputs for use in public engagement, presentations to policymakers. We were talking to them about collaborating on a energy system data project working in Python which is why I thought to add them here.

**Comment by hng** [comment]
I will close this for now but add the label "out of scope" to see how many coops would fit into other categories (or another list) in the future

**Pull request closed without merging**
